services:
  frontend:
    container_name: kpd-frontend
    image: kinduz90/kpd-frontend
    ports: 
      - "8080:80"
    networks:
      - external
    env_file:
      - .env

  backend:
    container_name: kpd-backend
    image: kinduz90/kpd-backend
    ports:
      - "4000:3000"
    networks:
      - internal
    depends_on:
      - postgres
    env_file: .env
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - internal
    
volumes:
  postgres_data:

networks:
  internal:
  external: